name: Docker Image CI

on:
  push:
    branches: [ "master" ]
<<<<<<< HEAD

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env.production for build
        run: |
          cat <<EOF > .env.production
          API_KEY=${{ secrets.API_KEY }}
          NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_RPC_URL=${{ secrets.NEXT_PUBLIC_RPC_URL }}
          NEXT_PUBLIC_API_URL=
          EOF

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            philipid3s/gold-bars-exchange-app:latest
            philipid3s/gold-bars-exchange-app:${{ github.sha }}
=======
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
>>>>>>> 0bab9e85af77e1623f8a553866b88be11e430a94
